### ISSUE TITLE
Not Related to Project. May I contact you about something?

### ISSUE THREAD

**Issue by H20Gamez** [Ooglely/pugBot#14]
Hi, I'm the head admin for TFArena and I am curious if our team can contact you about a project that we are wondering if you could be apart of. Thanks!

**Comment by Ooglely** [comment]
Hello, the best way to contact me right now would be on discord @waterfarer [(here)](https://discord.com/users/719269842276057280) or through the email I have linked on my github. I'm currently on a trip and don't have great internet access where I am staying, but I can try to get back to you whenever I am able to. :)
